apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-ecr-tagger
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-ecr-tagger-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-ecr-tagger-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-ecr-tagger-role
subjects:
- kind: ServiceAccount
  name: kube-ecr-tagger
  namespace: kube-system
---
