name: CI Build

on: 
  push:
    tags:
    - v*
    branches:
    - master
  pull_request:
    branches:
      - master

jobs:
  fmt:
    name: format
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run go formatter
      run: make fmt
  vet:
    name: vet
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run go vet
      run: make fmt
  lint:
    name: lint
    runs-on: ubuntu-latest
    needs: [fmt, vet]
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v2.0.0
      with:
        version: v1.28
  test:
    name: test
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run tests
      run: make test
    - name: Upload Coverage report to CodeCov
      uses: codecov/codecov-action@v1.0.11
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./coverage.out
  build-code:
    name: build code
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build binary
      run: make build
  docker-push:
    name: build and push docker image
    runs-on: ubuntu-latest
    needs: [build-code]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      if: github.event.base_ref == 'refs/heads/master'
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        repository: anesbenmerzoug/kube-ecr-tagger
        tag_with_ref: true
