name: CI

on: 
  push:
    branches:
    - master
  pull_request:

jobs:
  fmt:
    name: format
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
    - name: Check out code
      uses: actions/checkout@v2
    - name: Run go formatter
      run: make fmt
  vet:
    name: vet
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
    - name: Check out code
      uses: actions/checkout@v2
    - name: Run go vet
      run: make fmt
  lint:
    name: lint
    runs-on: ubuntu-latest
    needs: [fmt, vet]
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
    - name: Check out code
      uses: actions/checkout@v2
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v2.0.0
      with:
        version: v1.28
  test:
    name: test
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
    - name: Check out code
      uses: actions/checkout@v2
    - name: Run tests
      run: make test
    - name: Upload Coverage report to CodeCov
      uses: codecov/codecov-action@v1.0.11
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./coverage.out
  build:
    name: build
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
    - name: Check out code
      uses: actions/checkout@v2
    - name: Build binary
      run: make build
