name: CI

on: 
  push:
    branches:
    - master
  pull_request:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: Check out code
      uses: actions/checkout@v1
    - name: Install golangci-lint
      run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.22.0
    - name: Run golangci-lint
      run: make lint

  test:
    name: test
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: Check out code
      uses: actions/checkout@v1
    - name: Run tests
      run: make test
    - name: Upload Coverage report to CodeCov
      uses: codecov/codecov-action@v1.0.0
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./coverage.out
      
  build:
    name: build
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: Check out code
      uses: actions/checkout@v1
    - name: Build binary
      run: make build
